import 'package:firebase_auth/firebase_auth.dart';
import 'package:fluggle_app/services/auth_service.dart';
import 'package:fluggle_app/services/firebase_auth_service.dart';
import 'package:fluggle_app/services/firestore_database.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

/// Used to create user-dependent objects that need to be accessible by all widgets.
/// This widgets should live above the [MaterialApp].
/// See [AuthWidget], a descendant widget that consumes the snapshot generated by this builder.
class AuthWidgetBuilder extends StatelessWidget {
  const AuthWidgetBuilder({Key? key, required this.builder, required this.databaseBuilder}) : super(key: key);
  final Widget Function(BuildContext, AsyncSnapshot<FluggleAppUser?>) builder;
  final FirestoreDatabase Function(BuildContext context, String uid) databaseBuilder;

  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<FirebaseAuthService>(context, listen: false);
    return StreamBuilder<FluggleAppUser?>(
      stream: authService.onAuthStateChanged,
      builder: (BuildContext context, AsyncSnapshot<FluggleAppUser?> snapshot) {
        final FluggleAppUser? user = snapshot.data;
        if (user != null) {
          return MultiProvider(
            providers: [
              Provider<FluggleAppUser>.value(value: user),
              Provider<FirestoreDatabase>(
                create: (context) => databaseBuilder(context, user.uid),
              ),
              // NOTE: Any other user-bound providers here can be added here
            ],
            child: builder(context, snapshot),
          );
        }
        return builder(context, snapshot);
      },
    );
  }
}
